# Generated by Django 3.2.25 on 2025-05-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner Image')),
                ('call_to_action_link', models.URLField(blank=True, max_length=255, null=True)),
                ('call_to_action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('show_call_to_action', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Expired', 'Expired')], default='Active', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_location', models.CharField(choices=[('homepage__header', 'Homepage Header'), ('homepage__sidebar', 'Homepage Sidebar'), ('homepage__footer', 'Homepage Footer'), ('homepage__main', 'Homepage Main'), ('homepage__section_1', 'Homepage Section 1'), ('homepage__section_2', 'Homepage Section 2'), ('homepage__section_3', 'Homepage Section 3'), ('homepage__section_4', 'Homepage Section 4'), ('homepage__section_5', 'Homepage Section 5'), ('homepage__section_6', 'Homepage Section 6'), ('product_page__header', 'Product Page Header'), ('product_page__sidebar', 'Product Page Sidebar'), ('product_page__footer', 'Product Page Footer'), ('category_page__header', 'Category Page Header'), ('category_page__sidebar', 'Category Page Sidebar'), ('category_page__footer', 'Category Page Footer'), ('popup__main', 'Popup Main')], default='homepage__header', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-start_date'],
            },
        ),
    ]
