# Generated by Django 3.2.25 on 2025-06-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='display_location',
            field=models.CharField(choices=[('homepage__header', 'Homepage Header'), ('homepage__sidebar', 'Homepage Sidebar'), ('homepage__footer', 'Homepage Footer'), ('homepage__main', 'Homepage Main'), ('homepage__section_1', 'Homepage Section 1'), ('homepage__section_2', 'Homepage Section 2'), ('homepage__section_3', 'Homepage Section 3'), ('homepage__section_4', 'Homepage Section 4'), ('homepage__section_5', 'Homepage Section 5'), ('homepage__section_6', 'Homepage Section 6'), ('product_page__header', 'Product Page Header'), ('product_page__sidebar', 'Product Page Sidebar'), ('product_page__footer', 'Product Page Footer'), ('category_page__header', 'Category Page Header'), ('category_page__sidebar', 'Category Page Sidebar'), ('category_page__footer', 'Category Page Footer'), ('popup__main', 'Popup Main'), ('offers', 'Offers')], default='homepage__header', max_length=50),
        ),
    ]
