# Generated by Django 3.2.25 on 2025-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('Card', 'Card'), ('Esewa', 'Esewa')], default='cod', max_length=20),
        ),
    ]
