# Generated by Django 3.2.25 on 2025-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('cleaner', 'Cleaner'), ('supervisor', 'Supervisor'), ('senior supervisor', 'Senior Supervisor'), ('room attendee', 'Room Attendee'), ('admin', 'Admin'), ('staff', 'Staff'), ('hotel-contact-person', 'Hotel Contact Person')], max_length=20),
        ),
    ]
