[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    migrations
  | __pycache__
  | manage\.py
  | \.venv
  | hos_venv
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
skip = ["migrations", ".venv", "hos_venv"]
