# Generated by Django 3.2.25 on 2025-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_apikey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
