# Generated by Django 3.2.25 on 2025-05-12 08:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Full Description'),
        ),
    ]
