# Generated by Django 3.2.25 on 2025-05-25 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together'),
        ('orders', '0002_alter_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='carts.cart'),
        ),
    ]
