# Generated by Django 3.2.25 on 2025-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('Card', 'Card'), ('Esewa', 'Esewa')], default='COD', max_length=50),
        ),
    ]
