# Generated by Django 3.2.25 on 2025-05-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Privacy Policy'},
        ),
    ]
