name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: kinameldb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Load .env
        run: |
          echo "Loading environment variables from .env"
          export $(grep -v '^#' .env | xargs)

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Run migrations
        run: |
          export $(grep -v '^#' .env | xargs)
          python manage.py migrate

      - name: Collect static files
        run: |
          export $(grep -v '^#' .env | xargs)
          python manage.py collectstatic --noinput

      - name: Run tests
        run: |
          export $(grep -v '^#' .env | xargs)
          python manage.py test