# Generated by Django 3.2.25 on 2025-04-28 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sale', models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale'), ('Featured', 'Featured'), ('Best Seller', 'Best Seller'), ('Top Rated', 'Top Rated'), ('Limited Edition', 'Limited Edition'), ('Exclusive', 'Exclusive'), ('Clearance', 'Clearance'), ('Pre-Order', 'Pre-Order'), ('Backorder', 'Backorder'), ('Seasonal', 'Seasonal'), ('Limited Time Offer', 'Limited Time Offer'), ('Bundle', 'Bundle'), ('Gift Set', 'Gift Set'), ('Subscription', 'Subscription')], default='New', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Product Image')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Product Image 2')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Out Of Stock', 'Out Of Stock'), ('Disabled', 'Disabled')], default='Available', max_length=50)),
                ('location', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('sku', models.IntegerField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
