# Generated by Django 3.2.25 on 2025-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale'), ('Featured', 'Featured'), ('Best Seller', 'Best Seller'), ('Top Rated', 'Top Rated'), ('Limited Edition', 'Limited Edition'), ('Exclusive', 'Exclusive'), ('Clearance', 'Clearance'), ('Pre-Order', 'Pre-Order'), ('Backorder', 'Backorder'), ('Seasonal', 'Seasonal'), ('Limited Time Offer', 'Limited Time Offer'), ('Bundle', 'Bundle'), ('Gift Set', 'Gift Set'), ('Subscription', 'Subscription'), ('Trending', 'Trending'), ('Best Deal', 'Best Deal')], default='New', max_length=50, null=True),
        ),
    ]
